# Generated by Django 5.0.4 on 2024-05-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_book_delete_livre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rating',
        ),
    ]
